---
stages:
  - build
  - install
  - tests
  - lint
  - doc

default:
  tags:
    - yunohost-ci
  # All jobs are interruptible by default
  interruptible: true

variables:
  YNH_BUILD_DIR: "ynh-build"

include:
  - local: .gitlab/ci/*.gitlab-ci.yml
