########################################
# LINTER
########################################

lint:
  stage: lint
  image: "before-install"
  needs: []
  allow_failure: true
  script:
    - tox -e lint

invalidcode:
  stage: lint
  image: "before-install"
  needs: []
  script:
    - tox -e invalidcode

format-check:
  stage: lint
  image: "before-install"
  needs: []
  script:
    - black --check --diff
