########################################
# LINTER
########################################
# later we must fix lint and format-check jobs and remove "allow_failure"

lint39:
  stage: lint
  image: "before-install"
  needs: []
  allow_failure: true
  script:
    - tox -e py39-lint

invalidcode39:
  stage: lint
  image: "before-install"
  needs: []
  script:
    - tox -e py39-invalidcode

mypy:
  stage: lint
  image: "before-install"
  needs: []
  script:
    - tox -e py39-mypy
