########################################
# LINTER
########################################
# later we must fix lint and format-check jobs and remove "allow_failure"

lint:
  stage: lint
  image: "before-install"
  needs: []
  allow_failure: true
  script:
    - tox -e lint

invalidcode:
  stage: lint
  image: "before-install"
  needs: []
  script:
    - tox -e invalidcode

format-check:
  stage: lint
  image: "before-install"
  needs: []
  allow_failure: true
  script:
    - black --check --diff src doc data tests
